version: "2"

services:
  test-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/test/resources/db/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "max_wal_senders=4 "
      - "-c"
      - "wal_keep_size=4"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
    networks:
      - test-net

  test-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - test-net

  test-replicator:
    build: .
    environment:
      - POSTGRES_HOST=test-db
      - ELASTIC_HOST=test-es
    restart: unless-stopped
    networks:
      - test-net


volumes:
  db-data:
    driver: local
  es-data:
    driver: local

networks:
  test-net:
